import os, warnings
os.environ["OGR_ORGANIZE_POLYGONS"] = "SKIP"
warnings.filterwarnings("ignore")

import json
import geopandas as gpd
import pandas as pd
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output, callback
from pathlib import Path

DATA = Path(__file__).parents[2] / "data/raw"

# ── Helpers ───────────────────────────────────────────────────────────────────

def lines_to_latlons(gdf):
    """Return flat lat/lon lists (None-separated) for Scattermap."""
    lats, lons = [], []
    for geom in gdf.geometry:
        for part in (geom.geoms if hasattr(geom, "geoms") else [geom]):
            xs, ys = part.xy
            lons += list(xs) + [None]
            lats += list(ys) + [None]
    return lats, lons

# ── Load data ─────────────────────────────────────────────────────────────────
print("Loading data…")

# Trunk sewers
_ts = gpd.read_file(DATA / "sewers/Trunk Sewer - 4326.geojson")
_ts["install_year"] = pd.to_datetime(
    _ts["Trunk Sewer Install Date"], errors="coerce"
).dt.year.astype("Int64")
trunk = _ts[["install_year", "Trunk Sewer Material", "Trunk Sewer Diameter", "geometry"]].copy()
SEWER_YEAR_MIN = int(trunk["install_year"].dropna().min())

# Lost rivers — LASTDATE = year the river was last shown (i.e. when it was buried)
_lr = gpd.read_file(
    DATA / "rivers/doi-10.5683-sp2-tsjsqz/LostRiversData/Webmaps_data"
           "/LR_Toronto_Comp_WAS_geojson/BI_Lost_Rivers_20170705_WAMS_qgis.geojson"
).to_crs(4326)
_lr["last_year"] = _lr["LASTDATE"].dt.year.astype("Int64")
rivers = _lr[["last_year", "geometry"]].copy()
RIVER_YEAR_MIN = int(rivers["last_year"].dropna().min())

# Flood reports by neighbourhood (2013-2017)
_flood_shp_candidates = list((DATA / "floods/flood-reporting").glob("*.shp"))
if not _flood_shp_candidates:
    raise FileNotFoundError("No .shp in floods/flood-reporting/ — run fetch_data.py")
flood_rep = gpd.read_file(_flood_shp_candidates[0]).to_crs(4326)
FLOOD_REP_YEARS = [y for y in [2013, 2014, 2015, 2016, 2017]
                   if str(y) in flood_rep.columns]
flood_rep_geojson = json.loads(flood_rep.to_json())
for i, feat in enumerate(flood_rep_geojson["features"]):
    feat["id"] = i
FLOOD_REP_MAX = max(
    float(flood_rep[str(y)].max()) for y in FLOOD_REP_YEARS
)

# Ward boundaries + flooding xlsx
wards = gpd.read_file(DATA / "floods/city-wards-4326.geojson")
for col in wards.select_dtypes(include="datetime64[ns]"):
    wards[col] = wards[col].astype(str)
wards["ward_num"] = wards["AREA_SHORT_CODE"].astype(int)
wards = wards[["ward_num", "AREA_NAME", "geometry"]]

_raw = pd.read_excel(DATA / "floods/basement-flooding-by-ward.xlsx", header=None)
_df  = _raw.iloc[2:].copy()
_df.columns = list(range(20))
_df  = _df[_df[0].apply(lambda x: str(x).strip().isdigit())].copy()
_df[0] = _df[0].astype(int)
_df["ward_num"] = _df[0]
WARD_FLOOD_YEARS = list(range(2005, 2023))
_year_col = {y: i for i, y in enumerate(WARD_FLOOD_YEARS, start=1)}
ward_geojson = json.loads(wards.to_json())
for feat in ward_geojson["features"]:
    feat["id"] = feat["properties"]["ward_num"]
WARD_FLOOD_MAX = max(
    float(pd.to_numeric(_df[c], errors="coerce").max())
    for c in _year_col.values()
)

# Pre-extract river coords grouped by burial year (done once, not per callback)
_river_lats, _river_lons = {}, {}
for last_yr, grp in rivers.groupby("last_year"):
    _river_lats[last_yr], _river_lons[last_yr] = lines_to_latlons(grp)
_river_lats["all"], _river_lons["all"] = lines_to_latlons(rivers)

RIVER_YEAR_MAX = int(rivers["last_year"].dropna().max())
_ward_name = wards.set_index("ward_num")["AREA_NAME"].to_dict()
_flood_rep_names = flood_rep["AREA_NAME"].tolist()

# Annual precipitation (optional — generated by fetch_data.py)
_precip_path = DATA / "precipitation/toronto_annual_precip.csv"
if _precip_path.exists():
    _precip = pd.read_csv(_precip_path, index_col="year")
    print(f"  Precipitation: {len(_precip)} annual records loaded")
else:
    _precip = None

YEAR_MIN = min(SEWER_YEAR_MIN, RIVER_YEAR_MIN, 1850)
YEAR_MAX = 2022
print(f"Ready — year range {YEAR_MIN}–{YEAR_MAX}")

# ── Map builder ───────────────────────────────────────────────────────────────
def update(year):
    traces = []

    # 1 · Ward flooding choropleth (2005-2022)
    if year in _year_col:
        col = _year_col[year]
        wf = _df[["ward_num", col]].copy()
        wf.columns = ["ward_num", "count"]
        wf["count"] = pd.to_numeric(wf["count"], errors="coerce").fillna(0)
        z_ward, locs_ward = wf["count"].tolist(), wf["ward_num"].tolist()
        opacity_ward = 0.55
    else:
        z_ward, locs_ward, opacity_ward = [0] * len(wards), wards["ward_num"].tolist(), 0.0
    ward_customdata = [[_ward_name.get(w, str(w))] for w in locs_ward]

    traces.append(go.Choroplethmap(
        geojson=ward_geojson, locations=locs_ward, z=z_ward,
        featureidkey="id",
        customdata=ward_customdata,
        colorscale="YlOrRd", zmin=0, zmax=WARD_FLOOD_MAX,
        marker=dict(opacity=opacity_ward, line=dict(width=0.5, color="#888")),
        name=f"Ward basement floods ({WARD_FLOOD_YEARS[0]}–{WARD_FLOOD_YEARS[-1]})",
        showlegend=True, showscale=bool(year in _year_col),
        hovertemplate="<b>%{customdata[0]}</b><br>Basement floods: %{z:.0f}<extra></extra>",
        colorbar=dict(title=dict(text="Ward<br>basement<br>floods", font=dict(color="white")),
                      thickness=12, len=0.35, x=1.0, y=0.75, tickfont=dict(color="white")),
    ))

    # 2 · Neighbourhood flood reports (2013-2017)
    yr_s = str(year)
    if yr_s in flood_rep.columns:
        z_rep = pd.to_numeric(flood_rep[yr_s], errors="coerce").fillna(0).tolist()
        op_rep = 0.65
    else:
        z_rep, op_rep = [0] * len(flood_rep), 0.0

    traces.append(go.Choroplethmap(
        geojson=flood_rep_geojson,
        locations=list(range(len(flood_rep))), z=z_rep,
        featureidkey="id",
        customdata=[[n] for n in _flood_rep_names],
        colorscale=[[0, "rgba(0,0,0,0)"], [0.01, "#ffffcc"],
                    [0.5, "#fd8d3c"], [1, "#bd0026"]],
        zmin=0, zmax=FLOOD_REP_MAX,
        marker=dict(opacity=op_rep, line=dict(width=0.8, color="#ff6b6b")),
        name=f"Neighbourhood flood reports ({min(FLOOD_REP_YEARS)}–{max(FLOOD_REP_YEARS)})",
        showlegend=True, showscale=bool(yr_s in flood_rep.columns),
        hovertemplate="<b>%{customdata[0]}</b><br>Flood reports: %{z:.0f}<extra></extra>",
        colorbar=dict(title=dict(text="Neighbourhood<br>flood reports", font=dict(color="white")),
                      thickness=12, len=0.35, x=1.0, y=0.3, tickfont=dict(color="white")),
    ))

    # 3 · Trunk sewers built by this year
    mask = trunk["install_year"].notna() & (trunk["install_year"] <= year)
    built = trunk[mask]
    if len(built):
        lats, lons = lines_to_latlons(built)
        traces.append(go.Scattermap(
            lat=lats, lon=lons, mode="lines",
            line=dict(color="#e8a838", width=1.5),
            name=f"Trunk sewers (built ≤ {year})",
            hovertemplate="<b>Trunk sewer</b><br>Major underground conduits constructed on or before %{meta}<extra></extra>",
            meta=year,
        ))

    # 4 · Lost rivers — cyan if still flowing, grey if already buried
    still_lats, still_lons = [], []
    buried_lats, buried_lons = [], []
    for last_yr, lats_chunk in _river_lats.items():
        if last_yr == "all":
            continue
        lons_chunk = _river_lons[last_yr]
        if last_yr >= year:
            still_lats += lats_chunk
            still_lons += lons_chunk
        else:
            buried_lats += lats_chunk
            buried_lons += lons_chunk

    if still_lats:
        traces.append(go.Scattermap(
            lat=still_lats, lon=still_lons, mode="lines",
            line=dict(color="#4fc3f7", width=2.0),
            name=f"Lost rivers — still surface ({RIVER_YEAR_MIN}–{RIVER_YEAR_MAX})",
            hovertemplate="<b>Lost river (still flowing)</b><br>Visible on historical maps in %{meta}.<br>Dataset covers burial years %{customdata[0]}–%{customdata[1]}<extra></extra>",
            meta=year,
            customdata=[[RIVER_YEAR_MIN, RIVER_YEAR_MAX]] * len(still_lats),
        ))
    if buried_lats:
        traces.append(go.Scattermap(
            lat=buried_lats, lon=buried_lons, mode="lines",
            line=dict(color="#ce93d8", width=1.8),
            opacity=0.85,
            name=f"Lost rivers — already buried ({RIVER_YEAR_MIN}–{RIVER_YEAR_MAX})",
            hovertemplate="<b>Lost river (buried)</b><br>Channelled underground before %{meta}.<br>Dataset covers burial years %{customdata[0]}–%{customdata[1]}<extra></extra>",
            meta=year,
            customdata=[[RIVER_YEAR_MIN, RIVER_YEAR_MAX]] * len(buried_lats),
        ))

    fig = go.Figure(data=traces)

    if _precip is not None and year in _precip.index:
        row = _precip.loc[year]
        fig.add_annotation(
            text=(
                f"<b>Precipitation {year}</b><br>"
                f"Total: {row['precip_mm']:.0f} mm<br>"
                f"Rain: {row['rain_mm']:.0f} mm  Snow: {row['snow_cm']:.0f} cm<br>"
                f"Heavy-rain days (>25 mm): {int(row['heavy_days'])}"
            ),
            xref="paper", yref="paper",
            x=0.01, y=0.01, xanchor="left", yanchor="bottom",
            showarrow=False, align="left",
            font=dict(color="#ccc", size=11),
            bgcolor="rgba(13,17,23,0.78)", borderpad=6,
        )

    fig.update_layout(
        map_style="carto-darkmatter",
        map_center={"lat": 43.72, "lon": -79.40},
        map_zoom=10,
        paper_bgcolor="#0d1117",
        margin=dict(l=0, r=0, t=0, b=0),
        legend=dict(bgcolor="rgba(13,17,23,0.85)", font=dict(color="white", size=11),
                    x=0.01, y=0.99, xanchor="left", yanchor="top"),
        uirevision="constant",
    )
    return fig


# ── Historical map sequence ───────────────────────────────────────────────────
_UOT = "http://maps.library.utoronto.ca/datapub/digital/NG/historicTOmaps"

HIST_MAPS = [
    {
        "year": 1818,
        "title": "Plan of York — 1818  (Lieut. Phillpotts)",
        "url": f"{_UOT}/1818Phillpotts.mt-109x.jpg",
        "buried": [],
        "description": (
            "York (pop. ~1,200) occupies a small street grid between Yonge and Parliament. "
            "Every waterway is fully surface: Garrison Creek drains the western ravines to "
            "the lake near Strachan Ave; Taddle Creek runs south through what will become "
            "Queen's Park; Russell Creek drains the Annex. No sewers exist — open streams "
            "carry all runoff to the lake."
        ),
    },
    {
        "year": 1842,
        "title": "Cane Topographical Map — 1842",
        "url": f"{_UOT}/1842CaneF.jpeg",
        "buried": ["Lower Garrison Creek mouth (harbour infill for docks)"],
        "description": (
            "Toronto (renamed 1834, pop. ~15,000) expands along the waterfront. Harbour "
            "edges are filled in and creek mouths disappear beneath wharves. Garrison Creek "
            "still runs its full 7 km from the Davenport ridge to the lake. Park Creek feeds "
            "the western bay. Taddle Creek is open north of College Street."
        ),
    },
    {
        "year": 1851,
        "title": "Fleming Topographical Plan — 1851",
        "url": f"{_UOT}/1851flemingliberatedfromsid.jpeg",
        "buried": [
            "Lower Taddle Creek — College St to lake (first culvert)",
            "Russell Creek lower reach",
        ],
        "description": (
            "Population doubles to ~30,000. The lower Taddle Creek on College Street is "
            "culverted to create a road surface — Toronto's first deliberate creek burial. "
            "Russell Creek, draining the future Annex neighbourhood, begins to disappear "
            "downtown. Garrison Creek still runs openly through its full 7-km course."
        ),
    },
    {
        "year": 1858,
        "title": "Maclear's Sewer Plan — 1858",
        "url": f"{_UOT}/1858MaclearSewers.jpg",
        "buried": [
            "Taddle Creek — Queen St to lake",
            "Park Creek lower reach",
            "Several unnamed downtown ravine streams",
        ],
        "description": (
            "The first comprehensive sewer network is planned. Lower Taddle Creek from "
            "Queen St to the lake is incorporated into the sewer system and ceases to exist "
            "as a stream. Park Creek and ravine feeders south of Queen are channelled "
            "underground. The Don River's natural meanders, still fully intact here, will "
            "be straightened by engineers within 30 years."
        ),
    },
    {
        "year": 1882,
        "title": "McMurrich Parks Plan — 1882",
        "url": f"{_UOT}/1882McMurrichPlan.jpeg",
        "buried": [
            "Taddle Creek — Bloor St to Queen St (through university campus)",
            "Garrison Creek — King St to lake",
            "Russell Creek — entire lower half",
        ],
        "description": (
            "Population 86,000. Mayor McMurrich proposes a parks system along the remaining "
            "creek valleys — the last chance to preserve them as green corridors. The proposal "
            "is defeated. Taddle Creek through the university campus is now underground; only "
            "the ravine north of Bloor survives. Garrison Creek's lower half below King St "
            "has been replaced by a brick sewer."
        ),
    },
    {
        "year": 1888,
        "title": "Don River Straightening Plan — 1888  (Unwin, Browne & Sankey)",
        "url": f"{_UOT}/s0725_fl0012_MT00092C_don%20straightening.jpg",
        "buried": [
            "12 Don River tributary streams (meander cut-offs, 1886–1892)",
            "Lower Don natural meanders — channelled into straight cut",
        ],
        "description": (
            "Engineers propose straightening the lower 3 km of the Don into an artificial "
            "channel. Work begins in 1886 and finishes in 1892, burying 12 tributary streams "
            "that entered the old meanders. Ashbridge's Bay — fed by the natural Don delta — "
            "begins to be filled in for industrial use. The straight channel still carries the "
            "river today; the old meanders are now the DVP on-ramp at Eastern Ave."
        ),
    },
    {
        "year": 1888,
        "title": "Proposed Interceptor Sewers — 1888",
        "url": f"{_UOT}/1888Sewers.jpg",
        "buried": [
            "Garrison Creek — full 7-km course, Davenport to lake (brick tunnel)",
            "Taddle Creek — remaining Bloor-to-Davenport section",
        ],
        "description": (
            "A new interceptor sewer is engineered along the full course of Garrison Creek, "
            "replacing it mile by mile with a brick tunnel. By 1895 the creek is completely "
            "gone from the surface. The Garrison Creek Sewer remains the largest brick sewer "
            "in Canada and still carries stormwater under Garrison Creek Road today. Taddle "
            "Creek's last surface section north of Bloor is simultaneously buried as the "
            "neighbourhood is developed."
        ),
    },
    {
        "year": 1889,
        "title": "Intercepting Sewers & Outfall — 1889",
        "url": f"{_UOT}/1889.Toronto-Proposed-Intercepting-Sewers.s0725_fl0013_MT00098.jpg",
        "buried": [
            "Castle Frank Creek (east Don valley branch)",
            "Mud Creek (north Toronto — under Mt Pleasant Cemetery & Leaside)",
            "Brewery Creek (east end, St Lawrence Market area)",
            "All remaining waterways within the 1889 city boundary",
        ],
        "description": (
            "The expanded interceptor sewer network routes stormwater from all buried creeks "
            "to the lake outfall. Castle Frank Creek in the east Don valley is channelled. "
            "Mud Creek, running under Mount Pleasant Cemetery and Leaside, disappears. "
            "Brewery Creek in the east end is buried, ending the natural drainage of the "
            "St Lawrence Market area. Within the 1889 city boundary, only the Don River "
            "itself remains as an open watercourse."
        ),
    },
]

# ── App layout & callback ─────────────────────────────────────────────────────
app = Dash(__name__, suppress_callback_exceptions=True)
server = app.server  # expose Flask app for gunicorn / Render

TAB_STYLE = {
    "color": "#888", "backgroundColor": "#0d1117",
    "borderColor": "#2d2d2d", "padding": "8px 20px", "fontSize": "13px",
}
SEL_TAB_STYLE = {
    "color": "#fff", "backgroundColor": "#161b22",
    "borderTop": "2px solid #4fc3f7", "borderColor": "#2d2d2d",
    "padding": "8px 20px", "fontSize": "13px",
}
SLIDER_OVERLAY = {
    "position": "absolute", "bottom": "40px", "left": "50%",
    "transform": "translateX(-50%)", "width": "70%", "zIndex": "1000",
    "background": "rgba(13,17,23,0.82)", "borderRadius": "10px",
    "padding": "10px 24px 14px", "boxShadow": "0 2px 12px rgba(0,0,0,0.6)",
}

app.layout = html.Div(
    style={"height": "100vh", "display": "flex", "flexDirection": "column",
           "backgroundColor": "#0d1117", "fontFamily": "sans-serif"},
    children=[
        dcc.Tabs(
            id="main-tabs", value="tab-map",
            style={"flexShrink": "0"},
            colors={"border": "#2d2d2d", "primary": "#4fc3f7", "background": "#0d1117"},
            children=[
                dcc.Tab(label="Interactive Map", value="tab-map",
                        style=TAB_STYLE, selected_style=SEL_TAB_STYLE),
                dcc.Tab(label="Historical Maps", value="tab-history",
                        style=TAB_STYLE, selected_style=SEL_TAB_STYLE),
            ],
        ),
        # ── Tab 1 : interactive map ───────────────────────────────────────────
        html.Div(
            id="panel-map",
            style={"flex": "1", "position": "relative", "overflow": "hidden"},
            children=[
                dcc.Graph(id="map", figure=update(2015), style={"height": "100%"},
                          config={"scrollZoom": True}),
                html.Div(style=SLIDER_OVERLAY, children=[
                    html.Div("Toronto — Hidden Infrastructure & Flooding",
                             style={"color": "#e0e0e0", "fontSize": "13px",
                                    "textAlign": "center", "marginBottom": "6px",
                                    "letterSpacing": "0.5px"}),
                    dcc.Slider(
                        id="year-slider",
                        min=YEAR_MIN, max=YEAR_MAX, step=1, value=2015,
                        marks={y: {"label": str(y),
                                   "style": {"color": "#aaa", "fontSize": "11px"}}
                               for y in range(YEAR_MIN, YEAR_MAX + 1, 25)},
                        tooltip={"placement": "top", "always_visible": True},
                    ),
                ]),
            ],
        ),
        # ── Tab 2 : historical maps ───────────────────────────────────────────
        html.Div(
            id="panel-history",
            style={"flex": "1", "display": "none", "flexDirection": "column",
                   "overflow": "hidden", "padding": "12px 16px 8px"},
            children=[
                html.Div(
                    style={"flex": "1", "display": "flex", "gap": "14px",
                           "overflow": "hidden", "minHeight": "0"},
                    children=[
                        html.Div(
                            style={"flex": "1", "display": "flex",
                                   "justifyContent": "center", "alignItems": "center",
                                   "overflow": "hidden", "minWidth": "0"},
                            children=[
                                html.Img(id="hist-img",
                                         src=HIST_MAPS[0]["url"],
                                         style={"maxHeight": "100%", "maxWidth": "100%",
                                                "objectFit": "contain",
                                                "borderRadius": "4px"}),
                            ],
                        ),
                        html.Div(
                            id="hist-desc",
                            style={"width": "280px", "flexShrink": "0",
                                   "backgroundColor": "#161b22", "borderRadius": "8px",
                                   "padding": "14px 16px", "overflowY": "auto",
                                   "color": "#ddd", "fontSize": "13px",
                                   "lineHeight": "1.6"},
                        ),
                    ],
                ),
                html.Div(
                    style={"flexShrink": "0", "backgroundColor": "rgba(22,27,34,0.92)",
                           "borderRadius": "8px", "padding": "10px 24px 12px",
                           "marginTop": "10px",
                           "boxShadow": "0 2px 8px rgba(0,0,0,0.5)"},
                    children=[
                        html.Div(id="hist-title",
                                 style={"color": "#e0e0e0", "fontSize": "13px",
                                        "textAlign": "center", "marginBottom": "6px",
                                        "letterSpacing": "0.4px"}),
                        dcc.Slider(
                            id="hist-slider",
                            min=0, max=len(HIST_MAPS) - 1, step=1, value=0,
                            marks={i: {"label": str(m["year"]),
                                       "style": {"color": "#aaa", "fontSize": "11px"}}
                                   for i, m in enumerate(HIST_MAPS)},
                            tooltip={"placement": "top", "always_visible": False},
                        ),
                    ],
                ),
            ],
        ),
    ],
)


@app.callback(
    Output("panel-map",     "style"),
    Output("panel-history", "style"),
    Input("main-tabs", "value"),
)
def switch_tab(tab):
    base_map  = {"flex": "1", "position": "relative", "overflow": "hidden"}
    base_hist = {"flex": "1", "display": "flex", "flexDirection": "column",
                 "overflow": "hidden", "padding": "12px 16px 8px"}
    if tab == "tab-map":
        return base_map, {**base_hist, "display": "none"}
    return {**base_map, "display": "none"}, base_hist


app.callback(Output("map", "figure"), Input("year-slider", "value"))(update)


@app.callback(
    Output("hist-img",   "src"),
    Output("hist-title", "children"),
    Output("hist-desc",  "children"),
    Input("hist-slider", "value"),
)
def update_hist(idx):
    m = HIST_MAPS[idx]
    buried_items = (
        [html.Li(b, style={"marginBottom": "3px"}) for b in m["buried"]]
        if m["buried"]
        else [html.Li("None documented for this period",
                      style={"color": "#888", "fontStyle": "italic"})]
    )
    desc_children = [
        html.P(m["description"], style={"marginTop": "0"}),
        html.Hr(style={"borderColor": "#333", "margin": "10px 0"}),
        html.P("Waterways buried by this period:",
               style={"fontWeight": "bold", "marginBottom": "6px", "color": "#4fc3f7"}),
        html.Ul(buried_items, style={"paddingLeft": "18px", "margin": "0"}),
    ]
    return m["url"], m["title"], desc_children


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8050))
    app.run(debug=False, host="0.0.0.0", port=port)
