import os, warnings
os.environ["OGR_ORGANIZE_POLYGONS"] = "SKIP"
warnings.filterwarnings("ignore")

import json
import geopandas as gpd
import pandas as pd
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output, callback
from flask import redirect, send_from_directory
from pathlib import Path

try:
    from app import hotspots          # package import (gunicorn / wsgi:application)
except ImportError:                   # script import (python app/main.py)
    import hotspots

DATA = Path(__file__).parents[1] / "data/raw"

# ── Helpers ───────────────────────────────────────────────────────────────────

def lines_to_latlons(gdf):
    """Return flat lat/lon lists (None-separated) for Scattermap."""
    lats, lons = [], []
    for geom in gdf.geometry:
        for part in (geom.geoms if hasattr(geom, "geoms") else [geom]):
            xs, ys = part.xy
            lons += list(xs) + [None]
            lats += list(ys) + [None]
    return lats, lons

# ── Load data ─────────────────────────────────────────────────────────────────
print("Loading data…")

# Trunk sewers
_ts = gpd.read_file(DATA / "sewers/Trunk Sewer - 4326.geojson")
_ts["install_year"] = pd.to_datetime(
    _ts["Trunk Sewer Install Date"], errors="coerce"
).dt.year.astype("Int64")
trunk = _ts[["install_year", "Trunk Sewer Material", "Trunk Sewer Diameter", "geometry"]].copy()
SEWER_YEAR_MIN = int(trunk["install_year"].dropna().min())

# Lost rivers — LASTDATE = year the river was last shown (i.e. when it was buried)
_lr = gpd.read_file(
    DATA / "rivers/doi-10.5683-sp2-tsjsqz/LostRiversData/Webmaps_data"
           "/LR_Toronto_Comp_WAS_geojson/BI_Lost_Rivers_20170705_WAMS_qgis.geojson"
).to_crs(4326)
_lr["last_year"] = _lr["LASTDATE"].dt.year.astype("Int64")
rivers = _lr[["last_year", "geometry"]].copy()
RIVER_YEAR_MIN = int(rivers["last_year"].dropna().min())

# Flood reports by neighbourhood (2013-2017)
_flood_shp_candidates = list((DATA / "floods/flood-reporting").glob("*.shp"))
if not _flood_shp_candidates:
    raise FileNotFoundError("No .shp in floods/flood-reporting/ — run fetch_data.py")
flood_rep = gpd.read_file(_flood_shp_candidates[0]).to_crs(4326)
FLOOD_REP_YEARS = [y for y in [2013, 2014, 2015, 2016, 2017]
                   if str(y) in flood_rep.columns]
flood_rep_geojson = json.loads(flood_rep.to_json())
for i, feat in enumerate(flood_rep_geojson["features"]):
    feat["id"] = i
FLOOD_REP_MAX = max(
    float(flood_rep[str(y)].max()) for y in FLOOD_REP_YEARS
)

# Ward boundaries + flooding xlsx
wards = gpd.read_file(DATA / "floods/city-wards-4326.geojson")
for col in wards.select_dtypes(include="datetime64[ns]"):
    wards[col] = wards[col].astype(str)
wards["ward_num"] = wards["AREA_SHORT_CODE"].astype(int)
wards = wards[["ward_num", "AREA_NAME", "geometry"]]

_raw = pd.read_excel(DATA / "floods/basement-flooding-by-ward.xlsx", header=None)
_df  = _raw.iloc[2:].copy()
_df.columns = list(range(20))
_df  = _df[_df[0].apply(lambda x: str(x).strip().isdigit())].copy()
_df[0] = _df[0].astype(int)
_df["ward_num"] = _df[0]
WARD_FLOOD_YEARS = list(range(2005, 2023))
_year_col = {y: i for i, y in enumerate(WARD_FLOOD_YEARS, start=1)}
ward_geojson = json.loads(wards.to_json())
for feat in ward_geojson["features"]:
    feat["id"] = feat["properties"]["ward_num"]
WARD_FLOOD_MAX = max(
    float(pd.to_numeric(_df[c], errors="coerce").max())
    for c in _year_col.values()
)

# Pre-extract river coords grouped by burial year (done once, not per callback)
_river_lats, _river_lons = {}, {}
for last_yr, grp in rivers.groupby("last_year"):
    _river_lats[last_yr], _river_lons[last_yr] = lines_to_latlons(grp)
_river_lats["all"], _river_lons["all"] = lines_to_latlons(rivers)

RIVER_YEAR_MAX = int(rivers["last_year"].dropna().max())
_ward_name = wards.set_index("ward_num")["AREA_NAME"].to_dict()
_flood_rep_names = flood_rep["AREA_NAME"].tolist()

# Annual precipitation (optional — generated by fetch_data.py)
_precip_path = DATA / "precipitation/toronto_annual_precip.csv"
if _precip_path.exists():
    _precip = pd.read_csv(_precip_path, index_col="year")
    print(f"  Precipitation: {len(_precip)} annual records loaded")
else:
    _precip = None

YEAR_MIN = min(SEWER_YEAR_MIN, RIVER_YEAR_MIN, 1850)
YEAR_MAX = 2022
print(f"Ready — year range {YEAR_MIN}–{YEAR_MAX}")

# ── Map builder ───────────────────────────────────────────────────────────────
def update(year):
    traces = []

    # 1 · Ward flooding choropleth (2005-2022)
    if year in _year_col:
        col = _year_col[year]
        wf = _df[["ward_num", col]].copy()
        wf.columns = ["ward_num", "count"]
        wf["count"] = pd.to_numeric(wf["count"], errors="coerce").fillna(0)
        z_ward, locs_ward = wf["count"].tolist(), wf["ward_num"].tolist()
        opacity_ward = 0.55
    else:
        z_ward, locs_ward, opacity_ward = [0] * len(wards), wards["ward_num"].tolist(), 0.0
    ward_customdata = [[_ward_name.get(w, str(w))] for w in locs_ward]

    traces.append(go.Choroplethmap(
        geojson=ward_geojson, locations=locs_ward, z=z_ward,
        featureidkey="id",
        customdata=ward_customdata,
        colorscale="YlOrRd", zmin=0, zmax=WARD_FLOOD_MAX,
        marker=dict(opacity=opacity_ward, line=dict(width=0.5, color="#888")),
        name=f"Ward basement floods ({WARD_FLOOD_YEARS[0]}–{WARD_FLOOD_YEARS[-1]})",
        showlegend=True, showscale=bool(year in _year_col),
        hovertemplate="<b>%{customdata[0]}</b><br>Basement floods: %{z:.0f}<extra></extra>",
        colorbar=dict(title=dict(text="Ward<br>basement<br>floods", font=dict(color="white")),
                      thickness=12, len=0.35, x=1.0, y=0.75, tickfont=dict(color="white")),
    ))

    # 2 · Neighbourhood flood reports (2013-2017)
    yr_s = str(year)
    if yr_s in flood_rep.columns:
        z_rep = pd.to_numeric(flood_rep[yr_s], errors="coerce").fillna(0).tolist()
        op_rep = 0.65
    else:
        z_rep, op_rep = [0] * len(flood_rep), 0.0

    traces.append(go.Choroplethmap(
        geojson=flood_rep_geojson,
        locations=list(range(len(flood_rep))), z=z_rep,
        featureidkey="id",
        customdata=[[n] for n in _flood_rep_names],
        colorscale=[[0, "rgba(0,0,0,0)"], [0.01, "#ffffcc"],
                    [0.5, "#fd8d3c"], [1, "#bd0026"]],
        zmin=0, zmax=FLOOD_REP_MAX,
        marker=dict(opacity=op_rep, line=dict(width=0.8, color="#ff6b6b")),
        name=f"Neighbourhood flood reports ({min(FLOOD_REP_YEARS)}–{max(FLOOD_REP_YEARS)})",
        showlegend=True, showscale=bool(yr_s in flood_rep.columns),
        hovertemplate="<b>%{customdata[0]}</b><br>Flood reports: %{z:.0f}<extra></extra>",
        colorbar=dict(title=dict(text="Neighbourhood<br>flood reports", font=dict(color="white")),
                      thickness=12, len=0.35, x=1.0, y=0.3, tickfont=dict(color="white")),
    ))

    # 3 · Trunk sewers built by this year
    mask = trunk["install_year"].notna() & (trunk["install_year"] <= year)
    built = trunk[mask]
    if len(built):
        lats, lons = lines_to_latlons(built)
        traces.append(go.Scattermap(
            lat=lats, lon=lons, mode="lines",
            line=dict(color="#e8a838", width=1.5),
            name=f"Trunk sewers (built ≤ {year})",
            hovertemplate="<b>Trunk sewer</b><br>Major underground conduits constructed on or before %{meta}<extra></extra>",
            meta=year,
        ))

    # 4 · Lost rivers — cyan if still flowing, grey if already buried
    still_lats, still_lons = [], []
    buried_lats, buried_lons = [], []
    for last_yr, lats_chunk in _river_lats.items():
        if last_yr == "all":
            continue
        lons_chunk = _river_lons[last_yr]
        if last_yr >= year:
            still_lats += lats_chunk
            still_lons += lons_chunk
        else:
            buried_lats += lats_chunk
            buried_lons += lons_chunk

    if still_lats:
        traces.append(go.Scattermap(
            lat=still_lats, lon=still_lons, mode="lines",
            line=dict(color="#4fc3f7", width=2.0),
            name=f"Lost rivers — still surface ({RIVER_YEAR_MIN}–{RIVER_YEAR_MAX})",
            hovertemplate="<b>Lost river (still flowing)</b><br>Visible on historical maps in %{meta}.<br>Dataset covers burial years %{customdata[0]}–%{customdata[1]}<extra></extra>",
            meta=year,
            customdata=[[RIVER_YEAR_MIN, RIVER_YEAR_MAX]] * len(still_lats),
        ))
    if buried_lats:
        traces.append(go.Scattermap(
            lat=buried_lats, lon=buried_lons, mode="lines",
            line=dict(color="#ce93d8", width=1.8),
            opacity=0.85,
            name=f"Lost rivers — already buried ({RIVER_YEAR_MIN}–{RIVER_YEAR_MAX})",
            hovertemplate="<b>Lost river (buried)</b><br>Channelled underground before %{meta}.<br>Dataset covers burial years %{customdata[0]}–%{customdata[1]}<extra></extra>",
            meta=year,
            customdata=[[RIVER_YEAR_MIN, RIVER_YEAR_MAX]] * len(buried_lats),
        ))

    fig = go.Figure(data=traces)

    if _precip is not None and year in _precip.index:
        row = _precip.loc[year]
        fig.add_annotation(
            text=(
                f"<b>Precipitation {year}</b><br>"
                f"Total: {row['precip_mm']:.0f} mm<br>"
                f"Rain: {row['rain_mm']:.0f} mm  Snow: {row['snow_cm']:.0f} cm<br>"
                f"Heavy-rain days (>25 mm): {int(row['heavy_days'])}"
            ),
            xref="paper", yref="paper",
            x=0.01, y=0.01, xanchor="left", yanchor="bottom",
            showarrow=False, align="left",
            font=dict(color="#ccc", size=11),
            bgcolor="rgba(13,17,23,0.78)", borderpad=6,
        )

    fig.update_layout(
        map_style="carto-darkmatter",
        map_center={"lat": 43.72, "lon": -79.40},
        map_zoom=10,
        paper_bgcolor="#0d1117",
        margin=dict(l=0, r=0, t=0, b=0),
        legend=dict(bgcolor="rgba(13,17,23,0.85)", font=dict(color="white", size=11),
                    x=0.01, y=0.99, xanchor="left", yanchor="top"),
        uirevision="constant",
    )
    return fig


# ── River-change figure for a transition period ──────────────────────────────

def build_change_fig(before_year, after_year):
    """Plotly map: gray=already buried, orange=newly buried, cyan=still flowing."""
    already_lats, already_lons = [], []
    new_lats,     new_lons     = [], []
    still_lats,   still_lons   = [], []
    for last_yr, lats_chunk in _river_lats.items():
        if last_yr == "all":
            continue
        lons_chunk = _river_lons[last_yr]
        if last_yr < before_year:
            already_lats += lats_chunk; already_lons += lons_chunk
        elif last_yr <= after_year:
            new_lats     += lats_chunk; new_lons     += lons_chunk
        else:
            still_lats   += lats_chunk; still_lons   += lons_chunk

    traces = []
    if already_lats:
        traces.append(go.Scattermap(
            lat=already_lats, lon=already_lons, mode="lines",
            line=dict(color="#3a3a3a", width=1.0), name="Buried before",
            hovertemplate="<b>Buried before this period</b><extra></extra>",
        ))
    if still_lats:
        traces.append(go.Scattermap(
            lat=still_lats, lon=still_lons, mode="lines",
            line=dict(color="#4fc3f7", width=1.5), name="Still flowing after",
            hovertemplate="<b>Still flowing after this period</b><extra></extra>",
        ))
    if new_lats:
        traces.append(go.Scattermap(
            lat=new_lats, lon=new_lons, mode="lines",
            line=dict(color="#ff7043", width=3.0),
            name=f"Buried {before_year}–{after_year}",
            hovertemplate=f"<b>Buried {before_year}–{after_year}</b><extra></extra>",
        ))

    fig = go.Figure(data=traces)
    fig.update_layout(
        map_style="carto-darkmatter",
        map_center={"lat": 43.68, "lon": -79.38}, map_zoom=10,
        paper_bgcolor="#0d1117",
        margin=dict(l=0, r=0, t=0, b=0),
        legend=dict(bgcolor="rgba(13,17,23,0.85)", font=dict(color="white", size=10),
                    x=0.01, y=0.99, xanchor="left", yanchor="top"),
        uirevision=f"{before_year}-{after_year}",
    )
    return fig


# ── Historical map transition sequence ───────────────────────────────────────
_UOT  = "http://maps.library.utoronto.ca/datapub/digital/NG/historicTOmaps"
_WIKI = "https://commons.wikimedia.org/wiki/Special:FilePath"

HIST_TRANSITIONS = [
    {
        "before_year": 1818, "after_year": 1842,
        "before_title": "1818 — Plan of York (Phillpotts)",
        "after_title":  "1842 — Cane Topographical Map",
        "before_url": f"{_UOT}/1818Phillpotts.mt-109x.jpg",
        "after_url":  f"{_UOT}/1842CaneF.jpeg",
        "buried": ["Lower Garrison Creek mouth (harbour infill under new docks)"],
        "description": (
            "York (pop. ~1,200) sits in a small street grid east of Yonge. By 1842 it is "
            "Toronto (renamed 1834, pop. ~15,000). Harbour edges are filled for wharves and "
            "creek mouths begin to vanish. Garrison Creek, Taddle Creek, Russell Creek, and "
            "Park Creek all still run fully open. No engineered sewers exist — all drainage "
            "flows naturally to Lake Ontario."
        ),
    },
    {
        "before_year": 1842, "after_year": 1858,
        "before_title": "1842 — Cane Topographical Map",
        "after_title":  "1858 — Maclear's Sewer Plan",
        "before_url": f"{_UOT}/1842CaneF.jpeg",
        "after_url":  f"{_UOT}/1858MaclearSewers.jpg",
        "buried": [
            "Lower Taddle Creek — College St to lake (first deliberate culvert, c.1852)",
            "Russell Creek lower reach (south of Bloor)",
            "Park Creek lower reach",
        ],
        "description": (
            "Population doubles to ~30,000. The lower Taddle Creek on College Street is "
            "culverted c.1852 — Toronto's first deliberate creek burial. By 1858 engineer "
            "Maclear surveys a comprehensive sewer network that incorporates creek beds into "
            "brick conduits. The Don River's natural meanders are still fully intact. "
            "Garrison Creek still runs its full 7 km from Davenport Ridge to the lake."
        ),
    },
    {
        "before_year": 1858, "after_year": 1882,
        "before_title": "1858 — Maclear's Sewer Plan",
        "after_title":  "1882 — McMurrich Parks Plan",
        "before_url": f"{_UOT}/1858MaclearSewers.jpg",
        "after_url":  f"{_UOT}/1882McMurrichPlan.jpeg",
        "buried": [
            "Taddle Creek — through University of Toronto campus (1870s)",
            "Garrison Creek — King St to lake (lower half, brick sewer 1870s)",
            "Russell Creek — full lower half south of Dupont St",
        ],
        "description": (
            "Population reaches 86,000. Taddle Creek through the U of T campus is paved over; "
            "only the ravine north of Bloor survives. Garrison Creek's lower half is replaced "
            "by a brick sewer in the 1870s. In 1882, Mayor McMurrich proposes a parks system "
            "along remaining creek valleys — the last chance to preserve them as green corridors. "
            "The proposal is defeated by council. This decision seals the fate of every "
            "remaining open stream in the city."
        ),
    },
    {
        "before_year": 1882, "after_year": 1892,
        "before_title": "1882 — McMurrich Parks Plan",
        "after_title":  "1889 — Intercepting Sewers Plan",
        "before_url": f"{_UOT}/1882McMurrichPlan.jpeg",
        "after_url":  f"{_UOT}/1889.Toronto-Proposed-Intercepting-Sewers.s0725_fl0013_MT00098.jpg",
        "buried": [
            "Garrison Creek — full 7-km course, Davenport to lake (brick tunnel 1886–1892)",
            "Taddle Creek — remaining Bloor-to-Davenport ravine section",
            "Lower Don — 12 tributary streams cut off by meander straightening (1886–1892)",
            "Castle Frank Creek (east Don valley branch)",
            "Mud Creek — under Mount Pleasant Cemetery & Leaside",
            "Brewery Creek (St Lawrence Market area)",
        ],
        "description": (
            "The most dramatic decade of water erasure in Toronto's history. The Garrison Creek "
            "interceptor sewer (1886–1892) replaces the creek mile by mile with a brick tunnel — "
            "still the largest brick sewer in Canada. Simultaneously engineers straighten the "
            "lower 3 km of the Don, cutting off 12 tributary streams. Castle Frank Creek, Mud "
            "Creek, and Brewery Creek are all buried in the new interceptor network. Within the "
            "1889 city boundary, only the Don's main channel survives as open water."
        ),
    },
    {
        "before_year": 1892, "after_year": 1912,
        "before_title": "1889 — Intercepting Sewers Plan",
        "after_title":  "1910 — Goad's Atlas of Toronto",
        "before_url": f"{_UOT}/1889.Toronto-Proposed-Intercepting-Sewers.s0725_fl0013_MT00098.jpg",
        "after_url":  f"{_WIKI}/Toronto_1910_Atlas_General_Key.jpg",
        "buried": [
            "Black Creek upper reaches (Toronto Junction annexation, 1909)",
            "Mimico Creek tributaries (western annexations)",
            "Rosedale ravine streams — multiple tributaries buried under new streets",
        ],
        "description": (
            "Toronto annexes 16 surrounding municipalities between 1883 and 1914, each bringing "
            "new creek networks promptly sewered. The Garrison Creek Sewer is now complete and "
            "invisible on new maps. Black Creek's upper branches disappear under the expanding "
            "street grid of Toronto Junction (annexed 1909). Rosedale ravine streams vanish as "
            "wealthy estates give way to planned streets. The city triples in area; every "
            "expansion follows the same pattern: survey, sewer, build."
        ),
    },
    {
        "before_year": 1912, "after_year": 1954,
        "before_title": "1910 — Goad's Atlas of Toronto",
        "after_title":  "1956 — Nirenstein Business Map",
        "before_url":  f"{_WIKI}/Toronto_1910_Atlas_General_Key.jpg",
        "after_url":   f"{_WIKI}/Business_section_City_of_Toronto_1.jpg",
        "buried": [
            "Black Creek — full lower course (channelized for flood control, 1930s)",
            "Humber River tributaries (Etobicoke interwar expansion)",
            "East Toronto ravine networks (Scarborough border development)",
            "Don Valley small streams under industrial land use (1920s–1940s)",
        ],
        "description": (
            "Interwar expansion fills in the last open spaces. Black Creek, the largest "
            "surviving tributary network in the west end, is progressively channelized through "
            "the 1930s. On October 15, 1954, Hurricane Hazel drops 285 mm in 24 hours, killing "
            "81 people in the Humber and Don floodplains. The Toronto Region Conservation "
            "Authority is created the following year; its mandate is to channelize and control, "
            "not preserve. Flood-control works throughout the late 1950s bury or armour the "
            "last natural stream segments."
        ),
    },
    {
        "before_year": 1954, "after_year": 1975,
        "before_title": "1956 — Nirenstein Business Map (west)",
        "after_title":  "1956 — Nirenstein Business Map (east)",
        "before_url":  f"{_WIKI}/Business_section_City_of_Toronto_1.jpg",
        "after_url":   f"{_WIKI}/Business_section_City_of_Toronto_2.jpg",
        "buried": [
            "Don Valley tributaries — culverted under Don Valley Parkway (opened 1961)",
            "Mud Creek lower course — fully enclosed under Mt Pleasant Rd",
            "Taylor-Massey Creek upper — culverted under Scarborough subdivisions (1960s)",
            "Mimico Creek lower reach — armoured concrete channel (1960s)",
        ],
        "description": (
            "The highway era buries the last significant open tributaries. The Don Valley "
            "Parkway (1961) runs directly through the Don Valley, culverting every tributary "
            "at each crossing. The Gardiner Expressway (1955–1966) permanently severs the "
            "waterfront from downtown. Postwar subdivision expansion in Scarborough and "
            "Etobicoke routes stormwater through culverts. By 1975, fewer than 5% of "
            "Toronto's original stream network remains at surface — mostly within the ravine "
            "parks system that the 1882 McMurrich proposal had failed to protect."
        ),
    },
]

# ── App layout & callback ─────────────────────────────────────────────────────
app = Dash(__name__, suppress_callback_exceptions=True)
server = app.server  # expose Flask app for gunicorn / Render

# ── Scrollytelling story (static site in web/) served at /story ──────────────
STORY_DIR = Path(__file__).parents[1] / "web"

@server.route("/story")
def _story_redirect():
    return redirect("/story/")

@server.route("/story/")
def _story_index():
    return send_from_directory(STORY_DIR, "index.html")

@server.route("/story/<path:filename>")
def _story_asset(filename):
    return send_from_directory(STORY_DIR, filename)

TAB_STYLE = {
    "color": "#888", "backgroundColor": "#0d1117",
    "borderColor": "#2d2d2d", "padding": "8px 20px", "fontSize": "13px",
}
SEL_TAB_STYLE = {
    "color": "#fff", "backgroundColor": "#161b22",
    "borderTop": "2px solid #4fc3f7", "borderColor": "#2d2d2d",
    "padding": "8px 20px", "fontSize": "13px",
}
SLIDER_OVERLAY = {
    "position": "absolute", "bottom": "40px", "left": "50%",
    "transform": "translateX(-50%)", "width": "70%", "zIndex": "1000",
    "background": "rgba(13,17,23,0.82)", "borderRadius": "10px",
    "padding": "10px 24px 14px", "boxShadow": "0 2px 12px rgba(0,0,0,0.6)",
}

app.layout = html.Div(
    style={"height": "100vh", "display": "flex", "flexDirection": "column",
           "backgroundColor": "#0d1117", "fontFamily": "sans-serif"},
    children=[
        dcc.Tabs(
            id="main-tabs", value="tab-map",
            style={"flexShrink": "0"},
            colors={"border": "#2d2d2d", "primary": "#4fc3f7", "background": "#0d1117"},
            children=[
                dcc.Tab(label="Interactive Map", value="tab-map",
                        style=TAB_STYLE, selected_style=SEL_TAB_STYLE),
                dcc.Tab(label="Historical Maps", value="tab-history",
                        style=TAB_STYLE, selected_style=SEL_TAB_STYLE),
                dcc.Tab(label="Risk Hotspots", value="tab-hotspots",
                        style=TAB_STYLE, selected_style=SEL_TAB_STYLE),
            ],
        ),
        # ── Tab 1 : interactive map ───────────────────────────────────────────
        html.Div(
            id="panel-map",
            style={"flex": "1", "position": "relative", "overflow": "hidden"},
            children=[
                dcc.Graph(id="map", figure=update(2015), style={"height": "100%"},
                          config={"scrollZoom": True}),
                html.Div(style=SLIDER_OVERLAY, children=[
                    html.Div("Toronto — Hidden Infrastructure & Flooding",
                             style={"color": "#e0e0e0", "fontSize": "13px",
                                    "textAlign": "center", "marginBottom": "6px",
                                    "letterSpacing": "0.5px"}),
                    dcc.Slider(
                        id="year-slider",
                        min=YEAR_MIN, max=YEAR_MAX, step=1, value=2015,
                        marks={y: {"label": str(y),
                                   "style": {"color": "#aaa", "fontSize": "11px"}}
                               for y in range(YEAR_MIN, YEAR_MAX + 1, 25)},
                        tooltip={"placement": "top", "always_visible": True},
                    ),
                ]),
            ],
        ),
        # ── Tab 2 : historical maps ───────────────────────────────────────────
        html.Div(
            id="panel-history",
            style={"flex": "1", "display": "none", "flexDirection": "column",
                   "overflow": "hidden", "padding": "12px 16px 8px"},
            children=[
                # Before / After images (top, takes remaining flex space)
                html.Div(
                    style={"flex": "1", "display": "flex", "gap": "10px",
                           "overflow": "hidden", "minHeight": "0"},
                    children=[
                        # Before image
                        html.Div(
                            style={"flex": "1", "display": "flex", "flexDirection": "column",
                                   "overflow": "hidden", "minWidth": "0"},
                            children=[
                                html.Div(
                                    style={"display": "flex", "justifyContent": "space-between",
                                           "alignItems": "baseline", "marginBottom": "4px"},
                                    children=[
                                        html.Span("◀ BEFORE",
                                                  style={"color": "#4fc3f7", "fontSize": "10px",
                                                         "fontWeight": "bold", "letterSpacing": "1px"}),
                                        html.Span(id="hist-before-title",
                                                  style={"color": "#888", "fontSize": "10px",
                                                         "textAlign": "right"}),
                                    ],
                                ),
                                html.Div(
                                    style={"flex": "1", "display": "flex", "justifyContent": "center",
                                           "alignItems": "center", "overflow": "hidden", "minHeight": "0"},
                                    children=[
                                        html.Img(id="hist-before-img",
                                                 src=HIST_TRANSITIONS[0]["before_url"],
                                                 style={"maxHeight": "100%", "maxWidth": "100%",
                                                        "objectFit": "contain", "borderRadius": "4px"}),
                                    ],
                                ),
                            ],
                        ),
                        # After image
                        html.Div(
                            style={"flex": "1", "display": "flex", "flexDirection": "column",
                                   "overflow": "hidden", "minWidth": "0"},
                            children=[
                                html.Div(
                                    style={"display": "flex", "justifyContent": "space-between",
                                           "alignItems": "baseline", "marginBottom": "4px"},
                                    children=[
                                        html.Span("AFTER ▶",
                                                  style={"color": "#ce93d8", "fontSize": "10px",
                                                         "fontWeight": "bold", "letterSpacing": "1px"}),
                                        html.Span(id="hist-after-title",
                                                  style={"color": "#888", "fontSize": "10px",
                                                         "textAlign": "right"}),
                                    ],
                                ),
                                html.Div(
                                    style={"flex": "1", "display": "flex", "justifyContent": "center",
                                           "alignItems": "center", "overflow": "hidden", "minHeight": "0"},
                                    children=[
                                        html.Img(id="hist-after-img",
                                                 src=HIST_TRANSITIONS[0]["after_url"],
                                                 style={"maxHeight": "100%", "maxWidth": "100%",
                                                        "objectFit": "contain", "borderRadius": "4px"}),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
                # Change map + description (fixed 260 px row)
                html.Div(
                    style={"flexShrink": "0", "height": "260px", "display": "flex",
                           "gap": "10px", "marginTop": "8px", "overflow": "hidden"},
                    children=[
                        # Plotly change map
                        html.Div(
                            style={"flex": "2", "display": "flex", "flexDirection": "column",
                                   "minWidth": "0", "overflow": "hidden"},
                            children=[
                                html.Div(
                                    style={"display": "flex", "alignItems": "center",
                                           "gap": "8px", "marginBottom": "3px"},
                                    children=[
                                        html.Span("●", style={"color": "#ff7043", "fontSize": "12px"}),
                                        html.Span("Waterways buried in this period",
                                                  style={"color": "#ff7043", "fontSize": "10px",
                                                         "fontWeight": "bold", "letterSpacing": "0.5px"}),
                                        html.Span("●", style={"color": "#4fc3f7", "fontSize": "12px",
                                                              "marginLeft": "10px"}),
                                        html.Span("Still flowing after",
                                                  style={"color": "#4fc3f7", "fontSize": "10px"}),
                                        html.Span("●", style={"color": "#3a3a3a", "fontSize": "12px",
                                                              "marginLeft": "10px",
                                                              "WebkitTextStroke": "0.5px #888"}),
                                        html.Span("Buried before",
                                                  style={"color": "#888", "fontSize": "10px"}),
                                    ],
                                ),
                                dcc.Graph(
                                    id="hist-change-map",
                                    figure=build_change_fig(
                                        HIST_TRANSITIONS[0]["before_year"],
                                        HIST_TRANSITIONS[0]["after_year"],
                                    ),
                                    style={"flex": "1", "minHeight": "0"},
                                    config={"scrollZoom": True},
                                ),
                            ],
                        ),
                        # Description sidebar
                        html.Div(
                            id="hist-desc",
                            style={"flex": "1", "backgroundColor": "#161b22",
                                   "borderRadius": "8px", "padding": "12px 14px",
                                   "overflowY": "auto", "color": "#ddd",
                                   "fontSize": "12px", "lineHeight": "1.55",
                                   "minWidth": "0"},
                        ),
                    ],
                ),
                # Slider
                html.Div(
                    style={"flexShrink": "0", "backgroundColor": "rgba(22,27,34,0.92)",
                           "borderRadius": "8px", "padding": "10px 24px 12px",
                           "marginTop": "8px", "boxShadow": "0 2px 8px rgba(0,0,0,0.5)"},
                    children=[
                        html.Div(id="hist-title",
                                 style={"color": "#e0e0e0", "fontSize": "13px",
                                        "textAlign": "center", "marginBottom": "6px",
                                        "letterSpacing": "0.4px"}),
                        dcc.Slider(
                            id="hist-slider",
                            min=0, max=len(HIST_TRANSITIONS) - 1, step=1, value=0,
                            marks={i: {"label": str(t["before_year"]),
                                       "style": {"color": "#aaa", "fontSize": "11px"}}
                                   for i, t in enumerate(HIST_TRANSITIONS)},
                            tooltip={"placement": "top", "always_visible": False},
                        ),
                    ],
                ),
            ],
        ),
        # ── Tab 3 : risk hotspots ─────────────────────────────────────────────
        html.Div(
            id="panel-hotspots",
            style={"flex": "1", "display": "none", "flexDirection": "column",
                   "overflow": "hidden"},
            children=hotspots.panel_children(),
        ),
    ],
)


@app.callback(
    Output("panel-map",      "style"),
    Output("panel-history",  "style"),
    Output("panel-hotspots", "style"),
    Input("main-tabs", "value"),
)
def switch_tab(tab):
    base_map  = {"flex": "1", "position": "relative", "overflow": "hidden"}
    base_hist = {"flex": "1", "display": "flex", "flexDirection": "column",
                 "overflow": "hidden", "padding": "12px 16px 8px"}
    base_hot  = {"flex": "1", "display": "flex", "flexDirection": "column",
                 "overflow": "hidden"}
    hide = {"display": "none"}
    if tab == "tab-history":
        return {**base_map, **hide}, base_hist, {**base_hot, **hide}
    if tab == "tab-hotspots":
        return {**base_map, **hide}, {**base_hist, **hide}, base_hot
    return base_map, {**base_hist, **hide}, {**base_hot, **hide}


app.callback(Output("map", "figure"), Input("year-slider", "value"))(update)

hotspots.register_callbacks(app)


@app.callback(
    Output("hist-before-img",   "src"),
    Output("hist-after-img",    "src"),
    Output("hist-before-title", "children"),
    Output("hist-after-title",  "children"),
    Output("hist-title",        "children"),
    Output("hist-desc",         "children"),
    Output("hist-change-map",   "figure"),
    Input("hist-slider", "value"),
)
def update_hist(idx):
    t = HIST_TRANSITIONS[idx]
    buried_items = (
        [html.Li(b, style={"marginBottom": "3px", "fontSize": "11px"}) for b in t["buried"]]
        if t["buried"]
        else [html.Li("None documented",
                      style={"color": "#888", "fontStyle": "italic", "fontSize": "11px"})]
    )
    desc_children = [
        html.P(t["description"], style={"marginTop": "0", "marginBottom": "6px"}),
        html.Hr(style={"borderColor": "#333", "margin": "6px 0"}),
        html.P("Buried in this period:",
               style={"fontWeight": "bold", "marginBottom": "4px",
                      "color": "#ff7043", "fontSize": "11px"}),
        html.Ul(buried_items, style={"paddingLeft": "16px", "margin": "0"}),
    ]
    span = t["after_year"] - t["before_year"]
    title = f"{t['before_year']} → {t['after_year']}  ·  {span} years"
    return (
        t["before_url"],
        t["after_url"],
        t["before_title"],
        t["after_title"],
        title,
        desc_children,
        build_change_fig(t["before_year"], t["after_year"]),
    )


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8050))
    app.run(debug=False, host="0.0.0.0", port=port)
