"""Generate web/rivers-data.js from the Lost Rivers GeoJSON.

Reads the same Borealis Dataverse dataset the Dash app uses, simplifies the
polylines (Douglas-Peucker, pure stdlib — no geopandas needed), converts
Web-Mercator coordinates to true local meters, and writes a compact JS file
the story site loads with a plain <script> tag (works from file://).

Usage:  python web/tools/build_rivers_data.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = (ROOT / "data/raw/rivers/doi-10.5683-sp2-tsjsqz/LostRiversData/Webmaps_data"
       "/LR_Toronto_Comp_WAS_geojson/BI_Lost_Rivers_20170705_WAMS_qgis.geojson")
OUT = ROOT / "web/rivers-data.js"

R = 6378137.0                      # Web-Mercator sphere radius
SIMPLIFY_TOL_M = 9.0               # Douglas-Peucker tolerance (true meters)
MIN_SEG_M = 25.0                   # drop slivers shorter than this
DATASET_YEAR = 2017                # LASTDATE == 2017 → still at surface today


def merc_to_latlon(x, y):
    lon = math.degrees(x / R)
    lat = math.degrees(2.0 * math.atan(math.exp(y / R)) - math.pi / 2.0)
    return lat, lon


def dp_simplify(pts, tol):
    """Iterative Douglas-Peucker on [(x, y), …] in meters."""
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        i0, i1 = stack.pop()
        ax, ay = pts[i0]
        bx, by = pts[i1]
        dx, dy = bx - ax, by - ay
        seg2 = dx * dx + dy * dy
        dmax, imax = 0.0, -1
        for i in range(i0 + 1, i1):
            px, py = pts[i]
            if seg2 == 0.0:
                d = math.hypot(px - ax, py - ay)
            else:
                t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / seg2))
                d = math.hypot(px - (ax + t * dx), py - (ay + t * dy))
            if d > dmax:
                dmax, imax = d, i
        if dmax > tol:
            keep[imax] = True
            stack.append((i0, imax))
            stack.append((imax, i1))
    return [p for p, k in zip(pts, keep) if k]


def main():
    gj = json.loads(SRC.read_text())
    feats = gj["features"]

    # Pass 1 — convert to true local meters (equirectangular about the centroid)
    all_lat, all_lon = [], []
    parts = []                     # (burial_year, [(lat, lon), …])
    for f in feats:
        props = f["properties"]
        v = props.get("LASTDATE")
        year = int(str(v)[:4]) if v else DATASET_YEAR   # undated → assume survives
        for line in f["geometry"]["coordinates"]:
            ll = [merc_to_latlon(c[0], c[1]) for c in line]
            parts.append((year, ll))
            for lat, lon in ll:
                all_lat.append(lat)
                all_lon.append(lon)

    lat0 = sum(all_lat) / len(all_lat)
    kx = 111320.0 * math.cos(math.radians(lat0))   # m per deg lon
    ky = 110574.0                                  # m per deg lat
    lat_max, lon_min = max(all_lat), min(all_lon)

    def to_xy(lat, lon):           # screen-style: x east, y south, origin top-left
        return ((lon - lon_min) * kx, (lat_max - lat) * ky)

    # Pass 2 — simplify, measure, encode
    segs, total_m, buried_m, surface_m = [], 0.0, 0.0, 0.0
    pts_in = pts_out = 0
    w = h = 0.0
    for year, ll in parts:
        xy = [to_xy(lat, lon) for lat, lon in ll]
        pts_in += len(xy)
        length = sum(math.hypot(b[0] - a[0], b[1] - a[1]) for a, b in zip(xy, xy[1:]))
        if length < MIN_SEG_M:
            continue
        xy = dp_simplify(xy, SIMPLIFY_TOL_M)
        pts_out += len(xy)
        total_m += length
        if year >= DATASET_YEAR:
            surface_m += length
        else:
            buried_m += length
        flat = []
        for x, y in xy:
            flat.append(round(x))
            flat.append(round(y))
            w, h = max(w, x), max(h, y)
        segs.append({"y": year if year < DATASET_YEAR else 9999,
                     "km": round(length / 1000.0, 3), "p": flat})

    segs.sort(key=lambda s: s["y"])
    meta = {
        "w": round(w), "h": round(h),
        # projection constants so the site can place lat/lon labels:
        # x = (lon - lonMin) * kx ; y = (latMax - lat) * ky   (meters)
        "lonMin": round(lon_min, 6), "latMax": round(lat_max, 6),
        "kx": round(kx, 2), "ky": round(ky, 2),
        "totalKm": round(total_m / 1000.0, 1),
        "buriedKm": round(buried_m / 1000.0, 1),
        "surfaceKm": round(surface_m / 1000.0, 1),
        "nSegs": len(segs),
        "source": "Lost Rivers of Toronto — Borealis Dataverse doi:10.5683/SP2/TSJSQZ",
    }
    body = json.dumps({"meta": meta, "segs": segs}, separators=(",", ":"))
    OUT.write_text("// Generated by web/tools/build_rivers_data.py — do not edit.\n"
                   "window.RIVERS_DATA=" + body + ";\n")
    print(f"{SRC.name}: {len(feats)} features, {pts_in} pts → {pts_out} pts")
    print(f"network {meta['totalKm']} km | buried {meta['buriedKm']} km "
          f"| still surface {meta['surfaceKm']} km")
    print(f"wrote {OUT}  ({OUT.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
